{
 "title": "Solar",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Current",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "production_rms_current{type=\"eim\"}"
    }
   ]
  },
  {
   "title": "Prod today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "production_today_watthours{type=\"eim\"}"
    }
   ]
  },
  {
   "title": "Cons today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consumption_today_watthours{type=\"total-consumption\"}"
    }
   ]
  },
  {
   "title": "Net today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consumption_today_watthours{type=\"total-consumption\"} - ignoring(type) production_today_watthours{type=\"eim\"}"
    }
   ]
  },
  {
   "title": "Prod 7 days",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "production_7days_watthours" }
   ]
  },
  {
   "title": "Cons 7 days",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "consumption_7days_watthours{type=\"total-consumption\"}"
    }
   ]
  },
  {
   "title": "Net 7 days",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consumption_7days_watthours{type=\"total-consumption\"} - ignoring(type) production_7days_watthours{type=\"eim\"}"
    }
   ]
  },
  {
   "title": "Prod Lifetime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "production_lifetime_watthours{type=\"eim\"}"
    }
   ]
  },
  {
   "title": "Production",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "power_now_watts{type=\"eim\"}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "production_rms_voltage{type=\"eim\"}  "
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "production_rms_voltage{type=\"eim\"}",
     "legendFormat": "Voltage"
    }
   ]
  },
  {
   "title": "Current",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 3 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "production_rms_current{type=\"eim\"}",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Power Factor",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "production_power_factor{type=\"eim\"}"
    }
   ]
  },
  {
   "title": "Consumption",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consumption_now_watts{type=\"total-consumption\"}"
    }
   ]
  },
  {
   "title": "Total Power (theoretical max: 10.7kW AC)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "sum by(type) (power_now_watts)" }
   ]
  },
  {
   "title": "Power Factor",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "production_power_factor{type=\"eim\"}",
     "legendFormat": "Power Factor"
    }
   ]
  },
  {
   "title": "Net Consumption",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consumption_now_watts{type=\"net-consumption\"}"
    }
   ]
  },
  {
   "title": "Power by Array",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "sum by(location) (inverter_last_report_watts)"
    },
    {
     "expr": "max(sum by(location) (inverter_max_report_watts))",
     "legendFormat": "Max per array power"
    }
   ]
  },
  {
   "title": "Instantaneous Consumption",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "consumption_now_watts{type=\"net-consumption\"}",
     "legendFormat": "Net Consumption"
    },
    {
     "expr": "consumption_now_watts{type=\"total-consumption\"}",
     "legendFormat": "Total Consumption"
    },
    {
     "expr": "power_now_watts{type=\"eim\"}",
     "legendFormat": "Production"
    }
   ]
  },
  {
   "title": "Power by Inverter",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "avg by(serial, location) (inverter_last_report_watts)",
     "legendFormat": "{{location}} {{serial}}"
    },
    {
     "expr": "max (inverter_max_report_watts)"
    }
   ]
  },
  {
   "title": "Cumulative Consumption",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "consumption_today_watthours{type=\"total-consumption\"} - ignoring(type) production_today_watthours{type=\"eim\"}",
     "legendFormat": "Net Consumption"
    },
    {
     "expr": "consumption_today_watthours{type=\"total-consumption\"}",
     "legendFormat": "Total Consumption"
    },
    {
     "expr": "production_today_watthours{type=\"eim\"}",
     "legendFormat": "Production"
    },
    {
     "expr": "consumption_7days_watthours{type=\"total-consumption\"} - ignoring(type) production_7days_watthours{type=\"eim\"}",
     "legendFormat": "7 Day Net"
    }
   ]
  }
 ]
}